name: Composer dependency analyser

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer-dependency-analyser.php'
      - '.github/workflows/composer-dependency-analyser.yml'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer-dependency-analyser:
    uses: yiisoft/actions/.github/workflows/composer-dependency-analyser.yml@composer-dependency-analyzer
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4', '8.5']
