on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0']
      composer-command: >
        composer remove --dev ext-uopz &&
        composer remove --dev slope-it/clock-mock &&
        composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
